services:
  web:
    build:
      context: ../../
      dockerfile: docker/staging/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=music_game_app.settings.staging
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=localhost,127.0.0.1
    volumes:
      - static_volume:/app/staticfiles

volumes:
  static_volume: